name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build -c Release

      - name: Install local tools
        run: dotnet tool restore

      - name: Create temp directory
        run: mkdir temp

      - name: Generate Swagger document for WebApiOne
        run: dotnet swagger tofile --output temp/web-api-one.json src/WebApiOne/bin/Release/net8.0/WebApiOne.dll web-api-one

      - name: Generate OpenApi document for WebApiTwo
        run: dotnet swagger tofile --output temp/web-api-two.json src/WebApiTwo/bin/Release/net8.0/WebApiTwo.dll web-api-two

      - name: Copy OpenApi documents to docs
        run: cp -r temp/* docs/

      - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            branch: gh-pages # The branch the action should deploy to.
            folder: docs # The folder the action should deploy.
