name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build -c Release

      - name: Install local tools
        run: dotnet tool restore

      - name: Create temp directory
        run: mkdir temp

      - name: Generate Swagger for WebApiOne
        run: dotnet swagger tofile --output temp/web-api-one.json src/WebApiOne/bin/Release/net8.0/WebApiOne.dll web-api-one

      - name: Generate Swagger for WebApiTwo
        run: dotnet swagger tofile --output temp/web-api-two.json src/WebApiTwo/bin/Release/net8.0/WebApiTwo.dll web-api-two

      - name: Create gh-pages directory
        run: mkdir gh-pages

      - name: Copy Swagger files to gh-pages
        run: cp -r temp/* gh-pages/

      - name: Add CNAME file if you have a custom domain
        run: echo 'yourcustomdomain.com' > gh-pages/CNAME
        if: ${{ secrets.CUSTOM_DOMAIN }}

      - name: Commit and push to gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gh-pages
          git commit -m "Deploy Swagger JSON to GitHub Pages"
          git push origin `git subtree split --prefix gh-pages main`:gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
