name: Trigger Dispatch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger dispatch in target repository
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://github.com/diegosasw/nuget-api-sdk/dispatches \
          -d '{"event_type":"update-sdk"}'
